pentaho/pentaho-commons-database

pentaho-database-gwt/build-res/subfloor.xml
pentaho-database-model/build-res/subfloor.xml

Merge of master into future-develop

Auto-Merge refreshing development branch

---

pentaho-database-model/src/META-INF/services/org.pentaho.database.IDatabaseDialect
pentaho-database-model/src/org/pentaho/database/dialect/Hive2DatabaseDialect.java
pentaho-database-model/src/org/pentaho/database/dialect/Hive2SimbaDatabaseDialect.java
pentaho-database-model/src/org/pentaho/database/dialect/ImpalaSimbaDatabaseDialect.java
pentaho-database-model/src/org/pentaho/database/util/Const.java

Added Cloudera Impala Dialect (from Kettle)

[BACKLOG-4938] -  Impala Simba driver connection type is not present in BA server connection creating dialog

---

pentaho-database-model/src/org/pentaho/database/dialect/PDIDialect.java

[PDI-14421] Rename Pentaho Data Integration to Pentaho Data Services

---

pentaho-database-model/ivy.xml
pentaho-database-model/src/org/pentaho/database/dialect/PDIDialect.java
pentaho-database-model/test-src/org/pentaho/database/dialect/PDIDialectTest.java
pentaho-database-model/test-src/org/pentaho/database/service/DatabaseDialectServiceTest.java

Data Services: Test returns "Connection to database [kettle] succeeded"
http://jira.pentaho.com/browse/BACKLOG-5502

[BACKLOG-5502] Updated database name for test message

---

pentaho-database-gwt/ivy.xml
pentaho-database-gwt/src/org/pentaho/database/util/DatabaseUtil.java
pentaho-database-gwt/test-src/org/pentaho/database/util/DatabaseUtilTest.java

this is the same as https://github.com/pentaho/pentaho-commons-database/pull/87 but for 6.1
the backport has been requested by @kcruzada 
@hudak @tkafalas @e-cuellar @dkincade

[BACKLOG-6547] - CDH55 secure shim: PUC: DB Table(s) Data Source cannot be created based on Secured Cloudera Impala JDBC connection

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java
pentaho-database-gwt/src/org/pentaho/ui/database/resources/databasedialog.properties
pentaho-database-model/src/org/pentaho/database/dialect/PDIDialect.java
pentaho-database-model/test-src/org/pentaho/database/dialect/PDIDialectTest.java

Almost same changes as in kettle's dbdialog.
@mkambol

[BACKLOG-7483] Add the field "webapp name" for Pentaho Data Service database type (DSW)

---

pentaho-database-model/test-src/org/pentaho/database/service/DatabaseDialectServiceTest.java

[TEST] Fix failing test

---

pentaho-database-model/src/org/pentaho/database/service/ServiceLoaderDatabaseDialectProvider.java

- Loading IDatabaseDialect class  with the classloader that loaded the class, we are loading IDatabaseDialect  from.
- Checkstyle applied
@e-cuellar , could you please review it?
Purpose is absolutely same as for https://github.com/pentaho/pentaho-commons-database/pull/101

[PDI-15260] Model built using Spoon Agile is not getting published to the BA server.

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java

- If validationQuery is specified testOnBorrow automatically sets to true

[SP-3102][BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java

- If validationQuery is specified testOnBorrow automatically sets to true

[SP-3101][BISERVER-13407]-ValidationQuery and Pooling options not sent to DB when datasource is defined in Manage DataSources Perspective

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java

@mkambol Same changes as in https://github.com/pentaho/pentaho-kettle/pull/3389

[BACKLOG-8360] PUC-Default value changed from ‘pentaho-di’ to ‘Data Services’ after remove the default value from Web App Name and Saved it in PUC

---

pentaho-database-model/src/org/pentaho/database/dialect/PDIDialect.java

Fix for https://github.com/pentaho/pentaho-commons-database/commit/101949d6836a1b626a25d42f84ef067b80391be8#commitcomment-17334360
@pamval

[CLEANUP] Fix checkstyle violation

---

pentaho-database-model/src/org/pentaho/database/model/DatabaseType.java
pentaho-database-model/src/org/pentaho/database/util/DatabaseTypeHelper.java
pentaho-database-model/test-src/org/pentaho/database/service/DatabaseDialectServiceTest.java
pentaho-database-model/test-src/org/pentaho/database/util/DatabaseTypeHelperTest.java

- getting databasetype by name.toUpperCase
- added unit test

[BISERVER-13498]-The connection to MsSQLServer created in spoon doesn t display properly in PUC

---

pentaho-database-model/src/org/pentaho/database/util/DatabaseTypeHelper.java
pentaho-database-model/test-src/org/pentaho/database/util/DatabaseTypeHelperTest.java

- filling Map "databaseTypeByShortName" by uppercases names
- fix unit test

[BISERVER-13498]-The connection to MsSQLServer created in spoon doesnt display properly in PUC

---

pentaho-database-model/src/org/pentaho/database/model/DatabaseType.java
pentaho-database-model/src/org/pentaho/database/util/DatabaseTypeHelper.java
pentaho-database-model/test-src/org/pentaho/database/service/DatabaseDialectServiceTest.java
pentaho-database-model/test-src/org/pentaho/database/util/DatabaseTypeHelperTest.java

- getting databasetype by name.toUpperCase
- added unit test
- filling Map "databaseTypeByShortName" by uppercases names
- fix unit test

[SP-3380][BISERVER-13498]-The connection to MsSQLServer created in spoon doesnt display properly in PUC

---

pentaho-database-gwt/build-res/subfloor.xml
pentaho-database-gwt/src/build-res/version.properties
pentaho-database-model/build-res/subfloor.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java

-PDI and PUC dialogs should behave the same
-change default value empty rows for options from 5 to 15

[PDI-16778]-database connection > option section - can't add more than 4 parameters

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java

-PDI and PUC dialogs should behave the same
-change default value empty rows for options from 5 to 15

[SP-4117][PDI-16778]-database connection > option section - can't add more than 4 parameters

---

pentaho-database-gwt/src/org/pentaho/ui/database/event/DataHandler.java

[SP-4116][PDI-16778]-database connection > option section - can't add more than 4 parameters

---

gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog.xul

[BACKLOG-22736] Fix help icon color in the PUC DWC dialog so that it is theme specific

---

gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog_supported_languages.properties
gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog_zh_CN.properties

@pentaho/millenniumfalcon please review

[BACKLOG-25043] Simplified Chinese localization

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java

[BACKLOG-29422] Update and Validate In-Product Links in 8.3

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java
gwt/src/main/java/org/pentaho/ui/database/event/GwtFragmentHandler.java
gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog_en.properties
gwt/src/main/resources/org/pentaho/ui/database/resources/redshift_native.xul

including custom overlay for logging in to redshift using iam credentials

[BACKLOG-30899] - Redshift IAM credentials in PUC

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java
gwt/src/main/java/org/pentaho/ui/database/gwt/Base64ClientUtils.java

@ssamora 
@smmribeiro 
This PR does not have unit tests because the changes was related native methods/JavaScript code and GWT code.

[BISERVER-14396] - Manage Datasources Perspective transmits password in clear text using checkParams API

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java
gwt/src/main/java/org/pentaho/ui/database/gwt/Base64ClientUtils.java

[SP-5894] - Backport of BISERVER-14396 - Manage Datasources Perspective transmits password in clear text using checkParams API (8.3 Suite)

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java
gwt/src/main/java/org/pentaho/ui/database/gwt/Base64ClientUtils.java

[SP-5895] - Backport of BISERVER-14396 - Manage Datasources Perspective transmits password in clear text using checkParams API (9.1 Suite)

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java

@bcostahitachivantara @smmribeiro @renato-s

[BACKLOG-35714] Error in web console when opening database connection dialog

---

model/src/main/java/org/pentaho/database/dialect/OracleDatabaseDialect.java

This should fix the following Bug: https://jira.pentaho.com/browse/BISERVER-14835

[BISERVER-14835] Bug with TNS connections in OracleDatabaseDialect fixed.

---

test/pom.xml

[SP-6179][PPP-4654] Get commons-io version from parent pom

---

model/pom.xml
model/src/main/java/org/pentaho/database/model/DatabaseConnection.java
model/src/main/java/org/pentaho/database/model/IDatabaseConnection.java

@andreramos89 
@bcostahitachivantara 
@smmribeiro

[PDI-19604] - Connection related issues when Connection Pooling is enabled in transformations.

---

gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog.xul

[BACKLOG-36851] : Focus Visible - Accessibility -  PUC Home Page –Datasource Wizard

---

gwt/pom.xml
test/pom.xml

@smmribeiro 
@renato-s 
@bcostahitachivantara

[PPP-4802] - Vulnerable Component: hsqldb

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java
gwt/src/main/java/org/pentaho/ui/database/event/GwtFragmentHandler.java

Cherry pick
@pentaho/wcag - Please review

[BACKLOG-37559] - Database dialog connection type selection

---

gwt/pom.xml
test/pom.xml

Reverts pentaho/pentaho-commons-database#210

Revert "[PPP-4802] - Vulnerable Component: hsqldb"

---

model/pom.xml
model/src/main/java/org/pentaho/database/model/DatabaseConnection.java
model/src/main/java/org/pentaho/database/model/IDatabaseConnection.java

@andreramos89 
@bcostahitachivantara 
@smmribeiro 
Original PRs:
- https://github.com/pentaho/pentaho-commons-database/pull/206
- https://github.com/pentaho/pentaho-commons-database/pull/209

[SP-6346] - Backport of PDI-19604 - Connection related issues when Connection Pooling is enabled in transformations. (9.3 Suite)

---

gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog.xul

@pentaho/millenniumfalcon and @pentaho/wcag please review.
This PR needs to be merged with:
[https://github.com/pentaho/pentaho-commons-gwt-modules/pull/934](https://github.com/pentaho/pentaho-commons-gwt-modules/pull/934)
and
[https://github.com/pentaho/data-access/pull/1208](https://github.com/pentaho/data-access/pull/1208)

[BACKLOG-36862] - Page Zoom (AA) - Database Connection Dialog

---

gwt/src/main/resources/org/pentaho/ui/database/resources/databasedialog.xul

@pentaho/wcag Please review
This PR is part of https://github.com/pentaho/data-access/pull/1216

[BACKLOG-38108] In new data base connection window for Interactive report the other options for this connection are not visible

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java

Original PR:
- https://github.com/pentaho/pentaho-commons-database/pull/238

[SP-6386] - Backport of PDI-19601 - PDI - Unable to edit, test, explore, or use a connection created in PUC (9.3 Suite)

---

gwt/src/main/java/org/pentaho/ui/database/event/DataHandler.java

Original PR:
- https://github.com/pentaho/pentaho-commons-database/pull/238

[SP-6387] - Backport of PDI-19601 - PDI - Unable to edit, test, explore, or use a connection created in PUC (9.5 Suite)

---

gwt/pom.xml
model/pom.xml
pom.xml
test/pom.xml

[CLEANUP] updated versions via release version merger

Merging master into wcag

---

model/src/main/java/org/pentaho/database/dialect/GoogleBigQueryDatabaseDialect.java

[PPP-4782] -Vulnerable Component:Jackson Libraries
[PPP-4782]: https://hv-eng.atlassian.net/browse/PPP-4782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4782] -Vulnerable Component:Jackson Libraries

---

test/pom.xml

[PPP-4936]-Vulnerable Component -Guava
[PPP-4936]: https://hv-eng.atlassian.net/browse/PPP-4936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4936]-Vulnerable Component :Guava

---

gwt/src/main/resources/org/pentaho/ui/database/resources/databaseEditorDialog.css

@pentaho/millenniumfalcon please review
Related PR:
- https://github.com/pentaho/pentaho-commons-gwt-modules/pull/1013

fix: Database Connection dialog zoom issues [BACKLOG-39638]

---

model/src/main/java/org/pentaho/database/dialect/MySQLDatabaseDialect.java

[BISERVER-15027] MySQL8 database repository for pentaho server does not work properly with mysql8 jar
[BISERVER-15027]: https://hv-eng.atlassian.net/browse/BISERVER-15027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BISERVER-15027] MySQL8 database repository for pentaho server does not work properly with mysql8 jar

---

model/src/main/java/org/pentaho/database/dialect/MySQLDatabaseDialect.java

[Revert][BISERVER-15027]MySQL8 database repository for pentaho server does not work properly with mysql8 jar
[BISERVER-15027]: https://hv-eng.atlassian.net/browse/BISERVER-15027?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Revert][BISERVER-15027]MySQL8 database repository for pentaho server does not work properly with mysql8 jar

---

model/src/main/java/org/pentaho/database/dialect/SnowflakeDatabaseDialect.java

fix[PPP-5711] upgrade snowflake-jdbc to 3.24.0

---

gwt/pom.xml

This is a leftover from the previous PR #294

build[PPP-5751]: update version of gwt-user form 2.10.0 to 2.12.2
